### ISSUE TITLE
future request: Allow to set headers like Authentication

### ISSUE THREAD

**Issue by TylerTemp** [psygame/UnityWebSocket#15]
Hi,

It'll be helpful if this project can support setting custom headers. I'm using JWT authentication, and need to set header:

```
Authorization: Bearer <myToken>
```

for [websocket-sharp](https://github.com/sta/websocket-sharp#query-string-origin-header-and-cookies), it supports `HTTP Authentication (Basic/Digest)` by using `ws.SetCredentials ("nobita", "password", preAuth);`, which will add header:

```
Authorization: Basic <realmToken>
```

Cloud you please add a function to set headers like:

```csharp
ws= new WebSocket(address);
ws.SetHeader("Authorization", "Bearer " + myToken);
```

Thanks!

**Comment by orangeagain** [comment]
As I know browser not support set header

**Comment by TylerTemp** [comment]
Oh, I see. Sorry for the bother
