### ISSUE TITLE
no call OnClose (unplay editor) OnApplicationQuit

### ISSUE THREAD

**Issue by Avatarchik** [psygame/UnityWebSocket#16]

**Comment by psygame** [comment]
you can call websocket.CloseAsync active when OnApplication

**Comment by Avatarchik** [comment]
I call  websocket.CloseAsync but the subscription callback does not work "_websocket.OnClose += (object sender, CloseEventArgs e) =>{}"

**Comment by psygame** [comment]
may the application quit before the websocket closed, so we can't catch the callback of OnClose .
if you want execute some logic OnClose, try 
void OnApplicationQuit()
{
    websocket.CloseAsync();
    // directly execute the quit logic, do not consider whether socket is closed or not.
    the quit logic
}
